### ISSUE TITLE
Search - determine work to be done under maintenance

### ISSUE THREAD

**Issue by DiemBTran** [notch8/atla_digital_library#203]
Going to use this to gather search related issues.

*  ~~This was the term I couldnt get to work in a search Bible (O.T.) or Bible (N.T.) - I had to add this to a record, then view it and click the facet for it in order to find these, items using Bible (O.T.) as a subject, not searchable -  https://dl.atla.com/catalog?f%5Bsubject_sim%5D%5B%5D=Bible+%28O.T.%29&locale=en~~

*  ~~strip spaces at the start of subject field terms~~
*  **lowercase and uppercase become 2 separate terms - example Iron age and Iron Age. Ideally these should function as the same term**
*  ~~advanced search option?~~

**Comment by DiemBTran** [comment]
Christy July 2019

---

@orangewolf here is my update of what this is about:

1. ~~from above this as a subject "Bible (O.T.)" will not show up when you search for it. You can see it on this item i added it to here:  http://18.236.129.244/concern/works/kd17cz58k?locale=en~~

~~Is this just an issue with the search Hyrax uses or is it a fixable problem?~~

2. ~~What will it take to have advance search options? We may have to save this for the future, but would like to have all the info to give to Christine and Gillian. (maybe make this its own ticket to have the info somewhere?)~~

3. Can we verify what fields have capitalization normalizing applied to them? We had talked about adding this to Format Original for example. I think Ill add it to this doc we were tracking things in before https://docs.google.com/spreadsheets/d/1naH5DSZc6-RWCGjYxU2zNsYRxN8oAKPMbag-s16tR3c/edit#gid=2098369962

**Comment by labradford** [comment]
Check for bulkrax overrides or the bulkrax branch for atla

**Comment by alishaevn** [comment]
> lowercase and uppercase become 2 separate terms - example Iron age and Iron Age. Ideally these should function as the same term

I have a work with a subject and was able to find it doing a search for the subject completely lowercased (as it is on the work) and title cased.

<details>
<summary>work with subject "basketball"</summary>

![Image](https://user-images.githubusercontent.com/29032869/235956064-9eed1475-9dcf-4191-a807-0443f8db2a06.png)
</details>

<details>
<summary>search for "basketball"</summary>

![Image](https://user-images.githubusercontent.com/29032869/235955934-7d187313-77b1-4e04-8f65-6ef1b8cfbdc3.png)
</details>

<details>
<summary>search for "Basketball"</summary>

![Image](https://user-images.githubusercontent.com/29032869/235955876-5df7697c-6f3b-4b23-bf33-3f25f99e2fc3.png)
</details>

**Comment by labradford** [comment]
I think what they want is to normalize the format field so that all versions of a term look the same, no matter what the import spreadsheet/oai feed have in them.
basketball => Basketball
basketBall => Basketball
BasketBall => Basketball

**Comment by summer-cook** [comment]
@ckarpinski here is the list of fields that have normalized capitalization, as well as details about how the normalization is done. 

### Fields that have normalized capitalization

#### default bulkrax parse methods w/ normalized capitalization
subject  - lowercases full string & capitalizes first letter
 format_original  - lowercases full string & capitalizes first letter
resource_type - normalizes with `Hyrax::ResourceTypeService`

#### custom parse method overrides in DL
language - lowercases the full language 
types - normalizes with `Hyrax::ResourceTypeService`
format_digital - normalizes with `Hyrax::FormatsService`

**Comment by ckarpinski** [comment]
Hi - This is not about appearancs so much as it is about facets - the same words need to be together as a single facet. Doing a search will bring back the results for all of these yes. but what we do not want is the same exact word but with different capitalization to show as two separate facet values.

I am unclear on what "custom parse method" is about for language - we do not want languages to be in all lowercase letters and as far as I know this is not what happens - otherwise that list looks right.

**Comment by ckarpinski** [comment]
actually this ticket has many things on it but this last part at the end is facet related

**Comment by summer-cook** [comment]
This is what the last thing left on the ticket was, from 2019. Everything else that was crossed out was worked on in a different ticket.

> Can we verify what fields have capitalization normalizing applied to them? We had talked about adding this to Format Original for example. I think Ill add it to this doc we were tracking things in before https://docs.google.com/spreadsheets/d/1naH5DSZc6-RWCGjYxU2zNsYRxN8oAKPMbag-s16tR3c/edit#gid=2098369962

In terms of the facets, you are right, its not about the appearance of these fields, this ticket was about determining how the value is saved. Capitalization normalization affects the facets because it determines how the value is saved, and then the saved values are what would show up in the facets.

my answer above lists the fields that already have capitalization normalization, and details about how it is being done. The "custom parse methods" are overrides to bulkrax - custom work that was done in the app to normalize your fields. vs default methods are ones that come with bulkrax. These methods just determine what will happen to the field upon import.

Are there other fields that are not listed above that need to be normalized? If so, they would need to be on a separate ticket for future maintenance work.

**Comment by ckarpinski** [comment]
@summer-cook  i think in the end i just was wanting to be clear. our language field is not all lowercase, but it is working correctly so I think it is fine.
