### ISSUE TITLE
SPIKE: Security scan issues

### ISSUE THREAD

**Issue by jillpe** [notch8/atla_digital_library#204]
related: #252 #253 

# Summary

The goal of this ticket is to research and determine what needs to be done to resolve these issue.  

The issues that carry a score of 5 or higher are the ones that need to get resolved. For this round, only the top two problems qualify:

- Score 10.0: PHP Unsupported Version Detection
- Score 5.0: Web Application Information Disclosure 

# Accepted Criteria
- [x] plan to fix PHP Unsupported Version Detection
- [x] plan to fix Web Application Information Disclosure (not in new scan - marking complete, April Rieger, 4/14/23)
- [x] new tickets created.

**Comment by ckarpinski** [comment]
Hi all this is the second half of a previous post on slack. There was a PDF with the actual security scan that I posted for Rob a month or so ago. This above was in reply to Rob's question of which things in the scan to work on

**Comment by crisr15** [comment]
Both of these issues are on omeka (exhibits).

**Comment by crisr15** [comment]
New security scan

[2023-02-08 23_02_36_dl.atla.com_10895650_FAIL.pdf](https://github.com/scientist-softserv/atla_digitial_library/files/10927555/2023-02-08.23_02_36_dl.atla.com_10895650_FAIL.pdf)

**Comment by labradford** [comment]
Need to move Omeka repo from Gitlab to Github - 3
Set up github actions for Omeka - 5

**Comment by aprilrieger** [comment]
Upgrade PHP to not be outdated. Current is 8.2.X as of April 14, 2023. App has PHP version 5.4.

The Omeka Application version we are running 2.8, cannot handle php 8 and we will need to upgrade the omeka pplication to use 3.1. 

But I would suggest to get a brand new 3.1 application up and running with php 8 and mysql 8 and re-import.

We should also consider upgrading the mysql version from 5.0 to 8.0 in the process since mysql 5.7 is on end of life in October and the only supported version will be 8.0 at that time.

tickets: 
- https://github.com/scientist-softserv/atla_digital_library/issues/264
